Repository WildCodeSchool/orleans-202103-php-project-coachmoi, pull requests merged in 2021-06, with the labels that each got.

#24 Création footer avec changement couleur
  assets/app.js
  assets/images/coachmoi.png
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/include/_footer.html.twig
  yarn.lock
Labels: correction done, reviewed

#25 fix chemin includes et footer
  templates/base.html.twig
  templates/includes/_footer.html.twig
Labels: reviewed

#28 US01_A_navbar
  assets/styles/app.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  package-lock.json
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
Labels: correction done, reviewed

#29 US01_B_banner
  assets/images/banner.jpg
  assets/styles/app.scss
  assets/styles/banner.scss
  templates/home/index.html.twig
  templates/includes/_banner.html.twig
Labels: resolve conflict, reviewed

#30 Sprint02 PR01
  assets/app.js
  assets/images/banner.jpg
  assets/images/coachmoi.png
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  package-lock.json
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_banner.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  templates/layout_superadmin.html.twig
  yarn.lock
Labels: reviewed

#36 fix navbar
  templates/includes/_navbar.html.twig
Labels: reviewed

#39 fix color body
  assets/styles/app.scss
Labels: reviewed

#40 S02 us04 section salles page accueil
  assets/images/background-salles.jpg
  assets/styles/app.scss
  assets/styles/training_space.scss
  src/Controller/HomeController.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/Entity/TrainingSpace.php
  src/Repository/TrainingSpaceRepository.php
  templates/home/_training_space.html.twig
  templates/home/index.html.twig
Labels: correction done, reviewed

#27 S1 us02 activités
  assets/styles/app.scss
  composer.json
  composer.lock
  migrations/Version20210608143159.php
  src/Controller/HomeController.php
  src/DataFixtures/ActivityFixtures.php
  src/Entity/Activity.php
  src/Repository/ActivityRepository.php
  templates/home/_activities.html.twig
  templates/home/index.html.twig
Labels: correction done, reviewed

#44 S01 us06 footer
  templates/includes/_footer.html.twig
Labels: reviewed

#42 S01 us05 coach
  migrations/Version20210607100851.php
  migrations/Version20210607103100.php
  src/Controller/HomeController.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Coach.php
  src/Entity/User.php
  src/Repository/CoachRepository.php
  src/Repository/UserRepository.php
  templates/home/_coach.html.twig
  templates/home/index.html.twig
Labels: resolve conflict, reviewed

#48 fix error with date
  migrations/Version20210609173116.php
  src/DataFixtures/CoachFixtures.php
Labels: reviewed

#52 Dev to Master Sprint 2
  assets/images/background-salles.jpg
  assets/styles/app.scss
  assets/styles/training_space.scss
  composer.json
  composer.lock
  migrations/Version20210607100851.php
  migrations/Version20210607103100.php
  migrations/Version20210609173116.php
  src/Controller/HomeController.php
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Activity.php
  src/Entity/Coach.php
  src/Entity/TrainingSpace.php
  src/Entity/User.php
  src/Repository/ActivityRepository.php
  src/Repository/CoachRepository.php
  src/Repository/TrainingSpaceRepository.php
  src/Repository/UserRepository.php
  templates/home/_activities.html.twig
  templates/home/_coach.html.twig
  templates/home/_training_space.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: reviewed

#49 affichage 4 card
  src/Controller/HomeController.php
Labels: correction done, reviewed

#38 02 page activites
  src/Controller/ActivityController.php
  templates/activity/index.html.twig
  templates/home/_activities.html.twig
  templates/home/index.html.twig
  templates/includes/_activitybanner.html.twig
  templates/includes/_navbar.html.twig
Labels: correction done, reviewed

#51 Formatting
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/variables.scss
  templates/activity/index.html.twig
  templates/home/_activities.html.twig
  templates/home/_coach.html.twig
  templates/home/_training_space.html.twig
  templates/home/index.html.twig
  templates/includes/_activitybanner.html.twig
  templates/includes/_banner.html.twig
  templates/includes/_navbar.html.twig
Labels: reviewed

#53 Fix the style the section training space of the homepage
  src/DataFixtures/TrainingSpaceFixtures.php
  templates/home/_training_space.html.twig
Labels: resolve conflict, reviewed

#54 fix_migration
  migrations/Version20210607100851.php
  migrations/Version20210607103100.php
  migrations/Version20210609173116.php
  migrations/Version20210611083154.php
Labels: reviewed

#55 Dev to Master
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/variables.scss
  migrations/Version20210607100851.php
  migrations/Version20210607103100.php
  migrations/Version20210609173116.php
  migrations/Version20210611083154.php
  src/Controller/ActivityController.php
  src/Controller/HomeController.php
  src/DataFixtures/TrainingSpaceFixtures.php
  templates/activity/index.html.twig
  templates/home/_activities.html.twig
  templates/home/_coach.html.twig
  templates/home/_training_space.html.twig
  templates/home/index.html.twig
  templates/includes/_activitybanner.html.twig
  templates/includes/_banner.html.twig
  templates/includes/_navbar.html.twig
Labels: reviewed

#50 Page contact & vérification données
  config/packages/twig.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/contact/index.html.twig
  templates/contact/messageSent.html.twig
Labels: correction done, reviewed

#56 Fix activity
  templates/activity/index.html.twig
  templates/home/_activities.html.twig
Labels: reviewed

#75 Fix the content and style of cards: section Training Spaces of Home page
  assets/styles/training_space.scss
  assets/styles/variables.scss
  migrations/Version20210614090126.php
  src/Controller/HomeController.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/SpaceCategoryFixtures.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/Entity/SpaceCategory.php
  src/Entity/TrainingSpace.php
  src/Repository/SpaceCategoryRepository.php
  symfony.lock
  templates/base.html.twig
  templates/home/_training_space.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: reviewed

#76 création page coach
  src/Controller/CoachController.php
  templates/coach/index.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
Labels: reviewed

#85 Fix lien contact et mise en form footer
  templates/includes/_footer.html.twig
Labels: reviewed

#87 fix bg et bg contact
  assets/images/clean-gray-paper.png
  assets/styles/app.scss
  templates/coach/index.html.twig
  templates/contact/index.html.twig
Labels: reviewed

#84 FIX: activités responsive
  src/DataFixtures/ActivityFixtures.php
  templates/home/_activities.html.twig
Labels: reviewed

#86 Envoi message depuis la page contact & première mise en forme de l'email
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  templates/contact/index.html.twig
  templates/contact/layoutEmail.html.twig
  templates/contact/messageSentConfirmed.html.twig
  templates/contact/newMessageEmail.html.twig
Labels: correction done, reviewed

#82 Page Salle avec la carte temporaire
  assets/images/exercise-outdoor.jpg
  assets/images/visio-coach2.jpg
  assets/images/yoga-outdoor1.jpg
  assets/images/yoga-outdoor2.jpg
  src/Controller/TrainingSpaceController.php
  src/DataFixtures/TrainingSpaceFixtures.php
  templates/home/_training_space.html.twig
  templates/includes/_navbar.html.twig
  templates/training_space/index.html.twig
Labels: correction done, reviewed

#88 Dev to Master Sprint 3
  assets/images/clean-gray-paper.png
  assets/images/exercise-outdoor.jpg
  assets/images/visio-coach2.jpg
  assets/images/yoga-outdoor1.jpg
  assets/images/yoga-outdoor2.jpg
  assets/styles/app.scss
  assets/styles/training_space.scss
  assets/styles/variables.scss
  config/packages/twig.yaml
  config/services.yaml
  migrations/Version20210614090126.php
  src/Controller/CoachController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/TrainingSpaceController.php
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/SpaceCategoryFixtures.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/Entity/Contact.php
  src/Entity/SpaceCategory.php
  src/Entity/TrainingSpace.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  src/Repository/SpaceCategoryRepository.php
  symfony.lock
  templates/activity/index.html.twig
  templates/base.html.twig
  templates/coach/index.html.twig
  templates/contact/index.html.twig
  templates/contact/layoutEmail.html.twig
  templates/contact/messageSentConfirmed.html.twig
  templates/contact/newMessageEmail.html.twig
  templates/home/_activities.html.twig
  templates/home/_coach.html.twig
  templates/home/_training_space.html.twig
  templates/home/index.html.twig
  templates/includes/_activitybanner.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
  templates/training_space/index.html.twig
Labels: reviewed

#92 S02 us30 b page coach
  migrations/Version20210616132349.php
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Activity.php
  src/Entity/Coach.php
  templates/home/_coach.html.twig
Labels: reviewed

#90 Navbar section Super Admin
  src/Controller/SuperAdminController.php
  templates/includes/_navbarSuperAdmin.html.twig
  templates/layout_superadmin.html.twig
  templates/super_admin/index.html.twig
Labels: correction done, reviewed

#95 Fix bdd master
  migrations/Version20210618084512.php
Labels: reviewed

#96 fix fixtures 2
  migrations/Version20210616132349.php
  migrations/Version20210618090432.php
Labels: reviewed

#97 dev to master thanks Sylvain
  migrations/Version20210618090432.php
  src/Controller/SuperAdminController.php
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Activity.php
  src/Entity/Coach.php
  templates/home/_coach.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/layout_superadmin.html.twig
  templates/super_admin/index.html.twig
Labels: reviewed

#147 login
  config/packages/security.yaml
  migrations/Version20210618081825.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
  templates/includes/_navbar.html.twig
  templates/security/login.html.twig
Labels: reviewed

#148 FIX: Fixed issue with User roles, can now be null
  src/Entity/User.php
Labels: reviewed

#149 FIX: relinked Training Space and space Category
  src/Entity/SpaceCategory.php
Labels: reviewed

#157 Fix page contact
  assets/styles/app.scss
  src/Controller/ContactController.php
  src/Form/ContactType.php
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/contact/messageSentConfirmed.html.twig
  templates/contact/newMessageEmail.html.twig
  templates/includes/_flash.html.twig
Labels: reviewed

#159 changment container et faute
  templates/security/login.html.twig
Labels: reviewed

#161 S04 us14 availability
  migrations/Version20210622221832.php
  migrations/Version20210623133707.php
  src/DataFixtures/WeekdayFixtures.php
  src/Entity/Availability.php
  src/Entity/Weekday.php
  src/Form/AvailabilityType.php
  src/Repository/AvailabilityRepository.php
  src/Repository/WeekdayRepository.php
  templates/includes/_form_availability.html.twig
Labels: reviewed

#162 S04 us14 readinfos
  migrations/Version20210618081825.php
  migrations/Version20210618090432.php
  src/Controller/ProfileCoachController.php
  templates/layout_admin.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#164 11- Mes informations (user)
  assets/styles/app.scss
  assets/styles/profiles.scss
  src/Controller/ProfileClientController.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Repository/ClientRepository.php
  templates/profile_client/index.html.twig
Labels: correction done, reviewed

#165 correction dans le controller
  src/Controller/ProfileCoachController.php
Labels: reviewed

#167 Dev to MASTER
  assets/styles/admin_client.scss
  assets/styles/app.scss
  assets/styles/profiles.scss
  assets/styles/variables.scss
  config/packages/security.yaml
  migrations/Version20210622221832.php
  migrations/Version20210623092002.php
  migrations/Version20210623133707.php
  src/Controller/ContactController.php
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/WeekdayFixtures.php
  src/Entity/Availability.php
  src/Entity/Client.php
  src/Entity/SpaceCategory.php
  src/Entity/User.php
  src/Entity/Weekday.php
  src/Form/AvailabilityType.php
  src/Form/ContactType.php
  src/Form/RegistrationFormType.php
  src/Repository/AvailabilityRepository.php
  src/Repository/ClientRepository.php
  src/Repository/UserRepository.php
  src/Repository/WeekdayRepository.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/contact/messageSentConfirmed.html.twig
  templates/contact/newMessageEmail.html.twig
  templates/home/_activities.html.twig
  templates/includes/_flash.html.twig
  templates/includes/_form_availability.html.twig
  templates/includes/_navbar.html.twig
  templates/layout_admin.html.twig
  templates/profile_client/index.html.twig
  templates/profile_coach/index.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
Labels: reviewed

#168 11-READ Mes informations table Client
  assets/styles/app.scss
  src/Controller/ProfileClientController.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Entity/User.php
  templates/layout_profile.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/index.html.twig
Labels: reviewed

#169 fix de la BDD encore
  composer.json
  composer.lock
  migrations/Version20210622221832.php
  migrations/Version20210623133707.php
  migrations/Version20210625110300.php
  symfony.lock
Labels: reviewed

#170 taille cards
  templates/training_space/index.html.twig
Labels: reviewed
