Repository WildCodeSchool/orleans-202103-php-project-coachmoi, pull requests merged in 2021-07, with the labels that each got.

#178 11 read mes preferences client
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/PracticeLevelFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Entity/PracticeLevel.php
  src/Repository/PracticeLevelRepository.php
  templates/layout_profile.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/_preferences.html.twig
  templates/profile_client/index.html.twig
Labels: reviewed

#183 S05 us14 coach preferences
  src/Entity/Coach.php
  src/Entity/User.php
  templates/profile_coach/_information.html.twig
  templates/profile_coach/_preferences.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#187 fix navbar profil
  templates/layout_profile.html.twig
Labels: reviewed

#188 READ availability: Profile Client + Coach
  composer.json
  composer.lock
  migrations/Version20210625110300.php
  src/DataFixtures/AvailabilityFixtures.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Availability.php
  src/Entity/Client.php
  src/Entity/Coach.php
  src/Entity/TrainingSpace.php
  symfony.lock
  templates/layout_profile.html.twig
  templates/profile_client/_availability.html.twig
  templates/profile_client/index.html.twig
  templates/profile_coach/_availability.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#190 Fix style of profile client + coach
  templates/layout_profile.html.twig
  templates/profile_client/_availability.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/_preferences.html.twig
  templates/profile_client/index.html.twig
  templates/profile_coach/_availability.html.twig
  templates/profile_coach/_information.html.twig
  templates/profile_coach/_preferences.html.twig
  templates/profile_coach/index.html.twig
Labels: correction done, reviewed

#195 21 read coach booking
  src/Controller/CoachBookingController.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/CoachBookingFixtures.php
  src/Entity/Activity.php
  src/Entity/Client.php
  src/Entity/CoachBooking.php
  src/Form/CoachBookingType.php
  src/Repository/CoachBookingRepository.php
  templates/coach_booking/index.html.twig
  templates/layout_superadmin.html.twig
Labels: reviewed

#193 Fix user access
  config/packages/security.yaml
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
Labels: reviewed

#200 Fix Ajout Photo Profil Coach
  assets/images/avatar.png
  templates/profile_coach/_photo.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#202 Us26 read coach superadmin
  src/Controller/CoachBookingController.php
  src/Controller/SuperAdminController.php
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/show_coachs.html.twig
Labels: reviewed

#201 Show fiche réservation
  src/Controller/CoachBookingController.php
  templates/coach_booking/index.html.twig
  templates/coach_booking/show.html.twig
  templates/profile_client/_preferences.html.twig
Labels: correction done, reviewed

#203 11 read coach moi
  src/DataFixtures/CoachBookingFixtures.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Entity/Coach.php
  src/Entity/CoachBooking.php
  templates/profile_client/_availability.html.twig
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/_preferences.html.twig
  templates/profile_client/index.html.twig
Labels: reviewed

#204 Fix fixtures
  src/DataFixtures/AvailabilityFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: reviewed

#205 ajout texte donné par Franck
  templates/home/_training_space.html.twig
  templates/includes/_banner.html.twig
Labels: reviewed

#206 updated activities according to Franck
  src/DataFixtures/ActivityFixtures.php
Labels: reviewed

#207 Liste coachs par réservation - activité
  src/Controller/CoachBookingController.php
  src/Repository/CoachRepository.php
  templates/coach_booking/index.html.twig
  templates/coach_booking/list_availablecoachs.html.twig
  templates/coach_booking/show.html.twig
Labels: reviewed

#213 fix photos et titre
  migrations/Version20210705191711.php
  src/DataFixtures/ActivityFixtures.php
  src/DataFixtures/CoachBookingFixtures.php
Labels: reviewed

#214 14 read coachmoi
  src/DataFixtures/CoachBookingFixtures.php
  src/DataFixtures/CoachFixtures.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Coach.php
  src/Entity/CoachBooking.php
  templates/profile_coach/_coachmoi.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#218 Super admin espace by activity
  src/Controller/CoachBookingController.php
  src/DataFixtures/TrainingSpaceFixtures.php
  src/Entity/Activity.php
  src/Entity/TrainingSpace.php
  src/Repository/TrainingSpaceRepository.php
  templates/coach_booking/list_spaces.html.twig
  templates/coach_booking/show.html.twig
Labels: reviewed

#217 S05 us14 update coach profile
  src/Controller/ProfileCoachController.php
  src/Form/CoachType.php
  src/Form/UserType.php
  templates/profile_coach/_form.html.twig
  templates/profile_coach/edit.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#220 fix des routes et fautes
  src/Controller/CoachBookingController.php
  templates/coach_booking/show.html.twig
  templates/super_admin/index.html.twig
Labels: reviewed

#231 SuperAdmin update coach dans la fiche réservation
  src/Controller/CoachBookingController.php
  templates/coach_booking/list_availablecoachs.html.twig
  templates/coach_booking/show.html.twig
Labels: reviewed

#232 SuperAdmin update space dans la fiche réservation
  src/Controller/CoachBookingController.php
  templates/coach_booking/list_spaces.html.twig
  templates/coach_booking/show.html.twig
Labels: reviewed

#224 Ajout activité Super Admin
  migrations/Version20210705191711.php
  src/Controller/AdminActivityController.php
  src/Entity/Activity.php
  src/Form/ActivityType.php
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_activity/new.html.twig
  templates/admin_activity/show.html.twig
Labels: reviewed

#234 Fix navbar + add links
  templates/includes/_navbar.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/index.html.twig
Labels: reviewed

#235 Update coach photo
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  public/uploads/coaches/upload-60e7143912112348773547.jpg
  src/Entity/Coach.php
  src/Form/CoachType.php
  symfony.lock
  templates/profile_coach/_photo.html.twig
Labels: reviewed

#238 Fix sur 2 fichiers pour commit et erreur
  src/Entity/Activity.php
  templates/coach_booking/show.html.twig
Labels: reviewed

#236 fix style du profil coach
  assets/styles/profiles.scss
  templates/profile_coach/_availability.html.twig
  templates/profile_coach/_coachmoi.html.twig
  templates/profile_coach/_information.html.twig
  templates/profile_coach/_preferences.html.twig
  templates/profile_coach/index.html.twig
Labels: correction done, reviewed

#240 Fix photo requirement
  public/uploads/coaches/upload-60e7143912112348773547.jpg
  src/Form/CoachType.php
  templates/profile_coach/edit.html.twig
Labels: reviewed

#241 correction petites fautes
  src/DataFixtures/CoachBookingFixtures.php
  src/Entity/Coach.php
  templates/includes/_navbar.html.twig
Labels: reviewed

#248 Super admin list client
  src/Controller/SuperAdminController.php
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/show_clients.html.twig
Labels: reviewed

#250 34 super admin read space
  src/Controller/AdminSpaceController.php
  src/Form/TrainingSpaceType.php
  templates/admin_activity/index.html.twig
  templates/admin_space/_delete_form.html.twig
  templates/admin_space/_form.html.twig
  templates/admin_space/edit.html.twig
  templates/admin_space/index.html.twig
  templates/admin_space/new.html.twig
  templates/admin_space/show.html.twig
  templates/base.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/layout.html.twig
Labels: reviewed

#251 fix migration
  migrations/Version20210708190341.php
Labels: reviewed

#252 fix liens
  templates/includes/_navbar.html.twig
Labels: reviewed

#253 DEV -> MASTER
  migrations/Version20210708190341.php
  src/Controller/AdminSpaceController.php
  src/Controller/SuperAdminController.php
  src/Form/TrainingSpaceType.php
  templates/admin_activity/index.html.twig
  templates/admin_space/_delete_form.html.twig
  templates/admin_space/_form.html.twig
  templates/admin_space/edit.html.twig
  templates/admin_space/index.html.twig
  templates/admin_space/new.html.twig
  templates/admin_space/show.html.twig
  templates/base.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/layout.html.twig
  templates/super_admin/show_clients.html.twig
Labels: reviewed

#255 Superadmin upload image activity
  config/packages/vich_uploader.yaml
  migrations/Version20210708190341.php
  migrations/Version20210709112029.php
  src/Entity/Activity.php
  src/Form/ActivityType.php
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
Labels: reviewed

#259 Superadmin upload image space training
  config/packages/vich_uploader.yaml
  migrations/Version20210709125358.php
  src/Entity/TrainingSpace.php
  src/Form/TrainingSpaceType.php
  templates/admin_space/index.html.twig
Labels: reviewed

#265 Sort the booking list by date
  migrations/Version20210710214649.php
  src/Controller/CoachBookingController.php
  src/DataFixtures/CoachBookingFixtures.php
  src/Entity/CoachBooking.php
  templates/coach_booking/index.html.twig
Labels: reviewed

#270 fichiers remis apres suppression
  migrations/Version20210708190341-2.php
  public/uploads/coaches/avatar-60e80db6aa0c4976621604.png
Labels: reviewed

#266 21 superadmin bookings status
  migrations/Version20210710214649.php
  migrations/Version20210710224149.php
  src/Controller/CoachBookingController.php
  src/DataFixtures/BookingStatusFixtures.php
  src/DataFixtures/CoachBookingFixtures.php
  src/Entity/BookingStatus.php
  src/Entity/CoachBooking.php
  src/Repository/BookingStatusRepository.php
  templates/coach_booking/index.html.twig
Labels: correction done, reviewed

#272 11 update client client
  src/Controller/ProfileClientController.php
  src/Form/ClientType.php
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_form.html.twig
  templates/profile_client/edit.html.twig
  templates/profile_client/index.html.twig
Labels: reviewed

#271 DEV -> MASTER
  config/packages/translation.yaml
  config/packages/vich_uploader.yaml
  migrations/Version20210708190341-2.php
  migrations/Version20210709112029.php
  migrations/Version20210709125358.php
  migrations/Version20210710224149.php
  public/uploads/coaches/avatar-60e80db6aa0c4976621604.png
  src/Controller/CoachBookingController.php
  src/Controller/ProfileClientController.php
  src/Controller/SuperAdminController.php
  src/DataFixtures/BookingStatusFixtures.php
  src/DataFixtures/CoachBookingFixtures.php
  src/Entity/Activity.php
  src/Entity/BookingStatus.php
  src/Entity/CoachBooking.php
  src/Entity/SearchCoach.php
  src/Entity/TrainingSpace.php
  src/Form/ActivityType.php
  src/Form/ClientType.php
  src/Form/SearchCoachType.php
  src/Form/TrainingSpaceType.php
  src/Repository/ActivityRepository.php
  src/Repository/BookingStatusRepository.php
  src/Repository/CoachRepository.php
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_space/index.html.twig
  templates/coach_booking/index.html.twig
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_form.html.twig
  templates/profile_client/edit.html.twig
  templates/profile_client/index.html.twig
  templates/super_admin/show_coachs.html.twig
Labels: reviewed

#273 Filter booking by status
  src/Controller/CoachBookingController.php
  src/Entity/SearchBooking.php
  src/Form/SearchBookingType.php
  src/Repository/CoachBookingRepository.php
  templates/coach_booking/index.html.twig
Labels: correction done, reviewed

#263 Superadmin search client
  src/Controller/SuperAdminController.php
  src/Entity/SearchClient.php
  src/Form/SearchClientType.php
  src/Repository/ClientRepository.php
  templates/super_admin/show_clients.html.twig
Labels: correction done, reviewed

#274 filtre activité coté visiteur
  src/Controller/CoachController.php
  src/Form/SearchActivityType.php
  templates/coach/index.html.twig
Labels: reviewed

#275 ajouter le migration a été supprimé par mistake
  migrations/Version20210710214649.php
Labels: reviewed

#278 Remplaced the map by carousel photo
  src/DataFixtures/TrainingSpaceFixtures.php
  templates/training_space/index.html.twig
Labels: reviewed

#279 fix style profile client
  templates/profile_client/_availability.html.twig
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/_preferences.html.twig
  templates/profile_client/index.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#280 page cgu
  src/Controller/CguController.php
  templates/cgu/index.html.twig
  templates/layout.html.twig
Labels: reviewed

#276 Superadmin attribuer roles
  src/Controller/ProfileClientController.php
  src/Controller/RegistrationController.php
  src/Controller/SuperAdminController.php
  src/Controller/UserController.php
  src/Entity/Client.php
  src/Entity/CoachBooking.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
  templates/super_admin/show_clients.html.twig
  templates/super_admin/show_coachs.html.twig
  templates/super_admin/show_users.html.twig
Labels: reviewed

#281 SuperAdmin attribue les roles à utilisateurs
  src/Controller/SuperAdminController.php
  src/Form/EditUserType.php
  templates/super_admin/edit_user.html.twig
  templates/super_admin/show_users.html.twig
Labels: resolve conflict, reviews requested

#282 Fix profiles champs null
  templates/profile_client/_availability.html.twig
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/_preferences.html.twig
  templates/profile_coach/_information.html.twig
Labels: reviewed

#277 fix definition des photos
  assets/images/defaut-yoga.webp
  public/uploads/coaches/avatar-60e80db6aa0c4976621604.png
  templates/home/_coach.html.twig
  templates/profile_coach/_photo.html.twig
  templates/profile_coach/index.html.twig
Labels: correction done, reviewed

#283 Ajout disponibilité client
  src/Controller/ProfileClientController.php
  src/Form/ClientAvailabilityType.php
  templates/profile_client/_availability.html.twig
  templates/profile_client_availability/_delete_form.html.twig
  templates/profile_client_availability/_form.html.twig
  templates/profile_client_availability/edit.html.twig
  templates/profile_client_availability/index.html.twig
  templates/profile_client_availability/new.html.twig
  templates/profile_client_availability/show.html.twig
Labels: reviewed

#284 ajout du fichier migr non push
  migrations/Version20210713090004.php
Labels: reviewed

#287 added dropdown to navbar superadmin
  templates/includes/_navbarSuperAdmin.html.twig
Labels: reviewed

#285 display if coachbooking doesn't exist
  templates/profile_client/_coachmoi.html.twig
Labels: reviewed

#288 Superadmin index cards
  templates/admin_activity/index.html.twig
  templates/admin_space/index.html.twig
  templates/coach_booking/index.html.twig
  templates/super_admin/index.html.twig
  templates/super_admin/show_clients.html.twig
  templates/super_admin/show_coachs.html.twig
  templates/super_admin/show_users.html.twig
Labels: reviewed

#286 all coach fields are nullable
  migrations/Version20210713090911.php
  src/Entity/Coach.php
Labels: correction done, reviewed

#289 fix commit phpstan
  src/Controller/ProfileClientController.php
  templates/profile_client_availability/edit.html.twig
Labels: correction done, reviewed

#290 fix affichages du profil
  templates/profile_coach/_availability.html.twig
  templates/profile_coach/_coachmoi.html.twig
  templates/profile_coach/_photo.html.twig
  templates/profile_coach/_preferences.html.twig
Labels: reviewed

#293 fix readme
  README.md
Labels: reviewed

#330 fix liens footer
  templates/includes/_footer.html.twig
Labels: reviewed

#331 Correction assert file sur activity
  src/Entity/Activity.php
Labels: reviewed

#332 added constraints on Client's birthdate and budget
  src/Entity/Client.php
Labels: reviewed

#333 fix fautes orthographe et Franglish
  src/Form/SearchCoachType.php
  templates/home/_training_space.html.twig
  templates/profile_client_availability/_delete_form.html.twig
  templates/profile_client_availability/edit.html.twig
  templates/profile_client_availability/index.html.twig
  templates/profile_client_availability/new.html.twig
  templates/profile_client_availability/show.html.twig
  templates/profile_coach_availability/_delete_form.html.twig
  templates/profile_coach_availability/edit.html.twig
  templates/profile_coach_availability/index.html.twig
  templates/profile_coach_availability/new.html.twig
  templates/profile_coach_availability/show.html.twig
Labels: reviewed

#335 Issu 30
  .github/workflows/deploy_prod.yaml
  migrations/Version20210715083929.php
  src/Entity/CoachBooking.php
  src/Entity/TrainingSpace.php
  templates/admin_space/_form.html.twig
  templates/admin_space/index.html.twig
Labels: reviewed

#338 links user to client upon registration. diplays profile with client i…
  migrations/Version20210715091959.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/ClientType.php
  templates/profile_client/_preferences.html.twig
Labels: reviewed

#336 Activité pour coach disponible
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
Labels: correction done, reviewed

#342 fix du probleme de recherche
  src/Repository/CoachRepository.php
Labels: reviewed

#341 added link to CGU upon registration
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: reviewed

#343 Fix SUPERADMIN issues of activity
  migrations/Version20210715125732.php
  src/Controller/AdminActivityController.php
  src/Entity/Activity.php
  src/Form/ActivityType.php
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_activity/new.html.twig
  templates/admin_activity/show.html.twig
Labels: correction done, reviewed

#345 Fix 35
  src/Controller/SuperAdminController.php
  src/Entity/Coach.php
  src/Entity/User.php
  src/Form/EditUserType.php
Labels: reviewed

#347 Fix lien choisir
  templates/home/_activities.html.twig
Labels: reviewed

#349 Fix liens disponibilités tous profils
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
  templates/profile_coach_availability/edit.html.twig
Labels: reviewed

#358 Reorganized cards and button in homepage SuperAdmin
  templates/super_admin/index.html.twig
Labels: reviewed

#359 display clients even if no activity
  assets/styles/variables.scss
  templates/super_admin/show_clients.html.twig
Labels: reviewed

#360 Fix button retour ausite
  templates/layout_superadmin.html.twig
  templates/super_admin/index.html.twig
Labels: reviewed

#361 32 route fr
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminSpaceController.php
  src/Controller/CoachBookingController.php
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Controller/SuperAdminController.php
  src/Controller/UserController.php
Labels: resolve conflict, reviewed

#362 harmonised titles in pages, superadmin home and navbar
  templates/admin_activity/index.html.twig
  templates/admin_space/index.html.twig
  templates/coach_booking/index.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/index.html.twig
  templates/super_admin/show_clients.html.twig
  templates/super_admin/show_coachs.html.twig
  templates/super_admin/show_users.html.twig
Labels: resolve conflict, reviewed

#367 route edit profil
  templates/includes/_navbar.html.twig
Labels: reviewed

#365 traduction pages superadmin
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_activity/new.html.twig
  templates/admin_activity/show.html.twig
  templates/admin_space/_form.html.twig
  templates/admin_space/edit.html.twig
Labels: correction done, reviewed

#370 added links to footer, coach and client documents
  templates/includes/_footer.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_coach/_information.html.twig
Labels: reviewed

#372 a jout Condition modal
  templates/home/_activities.html.twig
Labels: reviewed

#374 Navbar retravaillée
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/admin_activity/edit.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
Labels: correction done, reviewed

#381 Accueil admin style
  templates/super_admin/index.html.twig
Labels: reviewed

#382 FIX-43
  src/Form/ActivityType.php
  src/Form/CoachType.php
  templates/admin_activity/edit.html.twig
  templates/admin_activity/show.html.twig
Labels: reviewed

#385 Fix 49
  src/Form/CoachType.php
Labels: reviewed

#386 fixed spelling mistakes in fixtures
  src/DataFixtures/BookingStatusFixtures.php
Labels: reviewed

#387 added link on logo in navbars
  templates/includes/_navbar.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
Labels: reviewed

#388 Barre de recherche sur une ligne
  src/Form/SearchBookingType.php
  templates/coach_booking/index.html.twig
Labels: reviewed

#389 modifié le style de profile coach
  templates/profile_coach/_availability.html.twig
  templates/profile_coach/_coachmoi.html.twig
  templates/profile_coach/_form.html.twig
  templates/profile_coach/_information.html.twig
  templates/profile_coach/_photo.html.twig
  templates/profile_coach/_preferences.html.twig
  templates/profile_coach/edit.html.twig
  templates/profile_coach/index.html.twig
Labels: reviewed

#391 Style disponibilié coach
  templates/profile_coach_availability/_delete_form.html.twig
  templates/profile_coach_availability/_form.html.twig
  templates/profile_coach_availability/edit.html.twig
  templates/profile_coach_availability/index.html.twig
  templates/profile_coach_availability/new.html.twig
  templates/profile_coach_availability/show.html.twig
Labels: reviewed

#392 Fix issue 55
  templates/profile_coach/_information.html.twig
Labels: reviewed

#395 fix mapping entity client-activity
  src/Entity/Client.php
Labels: reviewed

#396 Fix modification date de naissance
  src/Entity/Coach.php
  templates/profile_coach/_preferences.html.twig
Labels: correction done, reviewed

#400 securisé les routes coté superadmin
  src/Controller/AdminActivityController.php
  src/Controller/AdminSpaceController.php
Labels: reviewed

#403 Delete thedownloadbutton
  src/Form/ActivityType.php
  src/Form/CoachType.php
  src/Form/TrainingSpaceType.php
Labels: reviewed

#398 superadmin activity show if featured or not
  templates/admin_activity/index.html.twig
Labels: correction done, reviewed

#454 enlevé mentions légales et politique de confidentialité du footer. en…
  templates/includes/_footer.html.twig
Labels: reviewed

#453 texte dans cards est centré verticalement
  templates/home/_training_space.html.twig
Labels: reviewed

#456 espacé les champs du formulaire d'inscription
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: reviewed

#464 issue 74 ok bouton radio
  src/Form/CoachType.php
Labels: reviewed

#463 issue 85 ok suppression du champ description dans les espaces
  migrations/Version20210723162226.php
  src/Entity/TrainingSpace.php
  templates/admin_space/index.html.twig
Labels: reviewed

#461 issue 62 ok
  src/Form/SearchActivityType.php
  templates/coach/index.html.twig
Labels: reviewed

#462 issue 69 ok
  templates/profile_client_availability/new.html.twig
Labels: reviewed

#465 fix style profile client
  assets/styles/profiles.scss
  templates/profile_client/_availability.html.twig
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_information.html.twig
  templates/profile_client/_preferences.html.twig
  templates/profile_client/index.html.twig
Labels: reviewed

#470 issue 78 cohérence bouton ajout bouton retour a liste
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_space/edit.html.twig
  templates/admin_space/index.html.twig
  templates/coach_booking/index.html.twig
  templates/coach_booking/show.html.twig
  templates/super_admin/edit_user.html.twig
  templates/super_admin/show_clients.html.twig
  templates/super_admin/show_users.html.twig
Labels: reviewed

#455 changement des termes ok
  src/Form/ClientType.php
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/index.html.twig
Labels: correction done, reviewed

#468 fix 101 responsive cards coach
  templates/home/_coach.html.twig
Labels: reviewed

#469 issue 72 champ Véhicule dans le meme style que les autres
  templates/profile_coach/_information.html.twig
Labels: reviewed

#471 fix probleme affichage et petit spacing sur bouton ajouter
  src/Form/TrainingSpaceType.php
  templates/admin_space/index.html.twig
Labels: reviewed

#472 Fix 66
  src/Form/ClientType.php
  templates/profile_client/_preferences.html.twig
Labels: reviewed

#473 suppression affichage mail et ajout du nom user
  src/Controller/SuperAdminController.php
  src/Form/EditUserType.php
  templates/super_admin/edit_user.html.twig
Labels: reviewed

#475 Fix 79 superadmin client
  templates/coach_booking/index.html.twig
  templates/home/_activities.html.twig
  templates/super_admin/show_clients.html.twig
Labels: reviewed

#476 ajouté message expliquant que doit choisir activité en premier
  templates/profile_client/_coachmoi.html.twig
Labels: reviewed

#478 changement couleur bouton supprimer
  templates/admin_activity/_delete_form.html.twig
Labels: reviewed

#480 Supprimé bouton voir sur disponibilités client, et supprimé méthode s…
  src/Controller/ProfileClientController.php
  templates/profile_client_availability/_form.html.twig
  templates/profile_client_availability/index.html.twig
Labels: reviewed

#481 Fix upload coach
  src/Entity/Coach.php
Labels: reviewed

#482 changé budget pour tarif
  templates/super_admin/show_coachs.html.twig
Labels: reviewed

#484 fix 94, 95 minorfix
  templates/coach_booking/index.html.twig
Labels: reviewed

#486 Fix text and style for edit
  src/Form/ClientType.php
  src/Form/UserType.php
  templates/profile_client/_availability.html.twig
  templates/profile_client/_form.html.twig
  templates/profile_client/edit.html.twig
Labels: reviewed

#483 75 role superadmin
  assets/styles/variables.scss
  src/Entity/User.php
  templates/super_admin/show_users.html.twig
Labels: correction done, reviewed

#485 Fix 81
  templates/super_admin/show_coachs.html.twig
Labels: correction done, reviewed

#487 Fix 76
  src/Form/EditUserType.php
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/edit_user.html.twig
Labels: resolve conflict, reviewed

#489 fix button login
  templates/security/login.html.twig
Labels: reviewed

#488 Fix aptitude profile client
  templates/profile_client/_form.html.twig
  templates/profile_client/_information.html.twig
Labels: reviewed

#490 Fix 96
  templates/coach_booking/index.html.twig
Labels: reviewed

#492 Fix 90
  src/Controller/AdminActivityController.php
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
Labels: reviewed

#493 Fix 106 Style Availability - profile client
  templates/profile_client_availability/_delete_form.html.twig
  templates/profile_client_availability/_form.html.twig
  templates/profile_client_availability/edit.html.twig
  templates/profile_client_availability/index.html.twig
  templates/profile_client_availability/new.html.twig
  templates/profile_client_availability/show.html.twig
Labels: reviewed

#495 Logo and favicon
  assets/images/coachmoi.png
  assets/images/favicon.png
Labels: reviewed

#496 Fix edit coach
  src/Form/CoachType.php
  templates/profile_coach/_form.html.twig
  templates/profile_coach/_information.html.twig
  templates/profile_coach/edit.html.twig
Labels: reviewed

#497 Fix style space training
  src/Controller/AdminSpaceController.php
  src/Form/TrainingSpaceType.php
  templates/admin_space/_delete_form.html.twig
  templates/admin_space/_form.html.twig
  templates/admin_space/edit.html.twig
  templates/admin_space/index.html.twig
  templates/admin_space/new.html.twig
Labels: reviewed

#498 Fix error string search bar and a few style
  assets/styles/app.scss
  src/Form/SearchBookingType.php
  src/Repository/CoachBookingRepository.php
  templates/coach_booking/index.html.twig
Labels: reviewed

#491 activity photos affichées lorsqu'on upload une photo
  .gitignore
  src/DataFixtures/ActivityFixtures.php
Labels: correction done, reviewed

#503 réorganise les cards
  templates/home/_activities.html.twig
Labels: reviewed

#509 Error pages ok
  composer.json
  composer.lock
  symfony.lock
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: reviewed

#512 fix bug display on profile
  assets/styles/profiles.scss
Labels: reviewed

#506 58 home choice button link
  src/Controller/HomeController.php
  templates/home/_activities.html.twig
  templates/home/index.html.twig
Labels: correction done, reviewed

#508 Fix 107
  templates/admin_activity/index.html.twig
  templates/admin_space/index.html.twig
  templates/coach_booking/index.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/super_admin/index.html.twig
  templates/super_admin/show_clients.html.twig
  templates/super_admin/show_coachs.html.twig
  templates/super_admin/show_users.html.twig
Labels: correction done, reviewed

#515 Fix 109
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
  templates/profile_client_availability/_delete_form.html.twig
  templates/profile_client_availability/_form.html.twig
  templates/profile_client_availability/edit.html.twig
  templates/profile_coach_availability/_delete_form.html.twig
  templates/profile_coach_availability/_form.html.twig
  templates/profile_coach_availability/edit.html.twig
  templates/profile_coach_availability/index.html.twig
  templates/profile_coach_availability/new.html.twig
Labels: reviewed

#514 Fix style user
  src/Controller/SuperAdminController.php
  templates/super_admin/show_users.html.twig
Labels: correction done, reviewed

#518 Fix 67tris
  templates/profile_client/_coachmoi.html.twig
  templates/profile_coach/_coachmoi.html.twig
Labels: reviewed

#519 fix responsive profile client + coach
  templates/profile_client/_availability.html.twig
  templates/profile_client/_form.html.twig
  templates/profile_client_availability/_delete_form.html.twig
  templates/profile_client_availability/edit.html.twig
  templates/profile_client_availability/index.html.twig
  templates/profile_coach/_availability.html.twig
  templates/profile_coach_availability/_delete_form.html.twig
  templates/profile_coach_availability/edit.html.twig
  templates/profile_coach_availability/index.html.twig
Labels: reviewed

#520 Fix style admin activity
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_activity/new.html.twig
Labels: reviewed

#521 Dev -> Master
  .gitignore
  assets/styles/profiles.scss
  composer.json
  composer.lock
  src/Controller/HomeController.php
  src/Controller/ProfileClientController.php
  src/Controller/ProfileCoachController.php
  src/Controller/SuperAdminController.php
  src/DataFixtures/ActivityFixtures.php
  symfony.lock
  templates/admin_activity/_delete_form.html.twig
  templates/admin_activity/_form.html.twig
  templates/admin_activity/edit.html.twig
  templates/admin_activity/index.html.twig
  templates/admin_activity/new.html.twig
  templates/admin_space/index.html.twig
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/coach_booking/index.html.twig
  templates/home/_activities.html.twig
  templates/home/index.html.twig
  templates/includes/_navbarSuperAdmin.html.twig
  templates/profile_client/_availability.html.twig
  templates/profile_client/_coachmoi.html.twig
  templates/profile_client/_form.html.twig
  templates/profile_client_availability/_delete_form.html.twig
  templates/profile_client_availability/_form.html.twig
  templates/profile_client_availability/edit.html.twig
  templates/profile_client_availability/index.html.twig
  templates/profile_coach/_availability.html.twig
  templates/profile_coach/_coachmoi.html.twig
  templates/profile_coach_availability/_delete_form.html.twig
  templates/profile_coach_availability/_form.html.twig
  templates/profile_coach_availability/edit.html.twig
  templates/profile_coach_availability/index.html.twig
  templates/profile_coach_availability/new.html.twig
  templates/super_admin/edit_user.html.twig
  templates/super_admin/index.html.twig
  templates/super_admin/show_clients.html.twig
  templates/super_admin/show_coachs.html.twig
  templates/super_admin/show_users.html.twig
Labels: reviewed

#522 Fix style coach
  templates/super_admin/show_coachs.html.twig
Labels: reviewed

#523 Fix SuperAdmin style
  src/Controller/SuperAdminController.php
  src/Form/EditUserType.php
  templates/super_admin/edit_user.html.twig
  templates/super_admin/show_clients.html.twig
Labels: reviewed

#524 Fix style booking
  templates/coach_booking/list_availablecoachs.html.twig
  templates/coach_booking/list_spaces.html.twig
  templates/coach_booking/show.html.twig
Labels: reviewed

#525 faute a coach
  templates/includes/_footer.html.twig
Labels: reviewed

#532 ajouté icone de recherche sur les boutons, et mis boutons coach et es…
  templates/coach_booking/show.html.twig
Labels: reviewed
